# Generated by Django 5.1.2 on 2024-11-30 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_website', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('prof_image', models.ImageField(blank=True, null=True, upload_to='user_proifle/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='products_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='products_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('usertypes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='products.usertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('colour_stones', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='cus_products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_products', to='products.category')),
                ('usertypes', models.ManyToManyField(related_name='cus_products_usertype', to='products.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('new_status', models.CharField(choices=[('processed', 'Processed'), ('cad', 'CAD'), ('cam', 'CAM'), ('wax', 'WAX'), ('casting', 'Casting'), ('grilling', 'Grilling'), ('filling', 'filling'), ('pre polish', 'Pre Polish'), ('setting', 'Setting'), ('final polish', 'Final Polish'), ('rhoium', 'Rhoium'), ('final qc', 'Final QC'), ('certification', 'Certification'), ('invoice', 'Invoice'), ('out for delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='processed', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('color', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.customizedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedProductMultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cus_products/additional_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.customizedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FullCustomizedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_number', models.CharField(default=True, max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordercode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('new_status', models.CharField(choices=[('processed', 'Processed'), ('cad', 'CAD'), ('cam', 'CAM'), ('wax', 'WAX'), ('casting', 'Casting'), ('grilling', 'Grilling'), ('filling', 'filling'), ('pre polish', 'Pre Polish'), ('setting', 'Setting'), ('final polish', 'Final Polish'), ('rhoium', 'Rhoium'), ('final qc', 'Final QC'), ('certification', 'Certification'), ('invoice', 'Invoice'), ('out for delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='processed', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_customized_products', to='products.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_colors', to='products.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_customized_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FullCustomizedMultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cus_products/additional_images')),
                ('product_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_additional_images', to='products.fullcustomizedorder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(blank=True, max_length=255)),
                ('total_gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_diamond_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_colour_stones', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('colour_stones', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('usertypes', models.ManyToManyField(related_name='products_usertype', to='products.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('colour_stones', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
        ),
    ]
