# Generated by Django 5.1.2 on 2024-11-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedorder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
