# Generated by Django 5.1.2 on 2024-11-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedproduct',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
    ]
