# Generated by Django 5.1.2 on 2024-11-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customizedorder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcustomizedorder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
