# Generated by Django 5.1.2 on 2024-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_customizedproduct_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
