# Generated by Django 5.1.2 on 2024-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fullcustomizedorder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour_stones',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='diamond_weight',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
    ]
