# Generated by Django 5.1.2 on 2024-11-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_customizedproduct_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_address',
        ),
    ]
