# Generated by Django 5.1.2 on 2024-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_user_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_website',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
