# Generated by Django 5.1.2 on 2024-11-08 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_colour_stones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='colour_stones',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='diamond_weight',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='net_weight',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_colour_stones',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_diamond_weight',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_gross_weight',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_net_weight',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Enter a valid decimal number.')]),
        ),
    ]
