# Generated by Django 5.1.2 on 2024-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cart_colour_stones_alter_cart_diamond_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour_stones',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='diamond_weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
