# Generated by Django 5.1.2 on 2024-11-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_customizedproduct_colour_stones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='products.usertype'),
        ),
    ]
