# Generated by Django 5.1.2 on 2024-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_contactmessage_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('rose', 'Rose'), ('yellow', 'Yellow')], max_length=100),
        ),
    ]
