# Generated by Django 5.1.2 on 2024-11-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_color_product_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
    ]
