# Generated by Django 5.1.2 on 2024-11-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_colors_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
