# Generated by Django 5.1.2 on 2024-11-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedproduct',
            name='color',
        ),
    ]
