# Generated by Django 5.1.2 on 2024-11-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
